### ISSUE TITLE
Library needs to be updated for the 2.9 flexible display

### ISSUE THREAD

**Issue by jasonthenderson** [rickkas7/Adafruit_EPD_RK#2]
The 2.9 display requires that you call setBlackBuffer and setcolorBuffer.  Those members don't exist in this fork, but they do exist in the Adafruit fork.  Could you please pull the latest changes from Adafruit and update this library?

**Comment by rickkas7** [comment]
Sorry, I apparently lost a bunch of Github notification emails. I updated the 2.3.0 of Adafruit_EPD.
